# Generated by Django 4.0.6 on 2022-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_addresses_id_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='postal',
            field=models.IntegerField(),
        ),
    ]
