# Generated by Django 3.2.6 on 2022-07-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0003_alter_shipments_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentsPurpleship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('in-transit', 'In-Transit'), ('delivered', 'Delivered')], max_length=255)),
                ('test_mode', models.BooleanField(blank=True, null=True)),
                ('created_start', models.DateTimeField(auto_now_add=True)),
                ('created_end', models.DateTimeField(auto_now=True)),
                ('carrier_id', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
                ('offset', models.IntegerField()),
                ('carrier_name', models.CharField(choices=[('aramex', 'Aramex'), ('australiapost', 'Australiapost'), ('canadapost', 'Canadapost'), ('canpar', 'Canpar'), ('dhl_express', 'Dhl_Express'), ('dhl_universal', 'Dhl_Universal'), ('dicom', 'Dicom'), ('eshipper', 'Eshipper'), ('fedex', 'Fedex'), ('freightcom', 'Freightcom'), ('purolator', 'Purolator'), ('royalmail', 'Royalmail'), ('sendle', 'Sendle'), ('sf_express', 'Sf_Express'), ('tnt', 'Tnt'), ('ups', 'Ups'), ('usps', 'Usps'), ('usps_international', 'Usps_International'), ('yanwen', 'Yanwen')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='shipments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
