# Generated by Django 3.2.6 on 2022-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20220706_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentspurpleship',
            name='test_mode',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
