# Generated by Django 3.2.6 on 2022-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255)),
                ('weight_unit', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('packaging_type', models.CharField(max_length=255)),
                ('package_preset', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('is_document', models.CharField(max_length=255)),
                ('dimension_unit', models.CharField(max_length=255)),
            ],
        ),
    ]
