# Generated by Django 3.2.6 on 2022-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by', models.CharField(choices=[('sender', 'Sender'), ('recipient', 'Recipient'), ('third_party', 'Third_Party')], max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
            ],
        ),
    ]
