# Generated by Django 4.0.6 on 2022-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_options_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255)),
                ('weight_unit', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('packaging_type', models.CharField(max_length=255)),
                ('package_preset', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('is_document', models.CharField(max_length=255)),
                ('dimension_unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='content',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='description',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='dimension_unit',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='height',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='is_document',
            new_name='federal_tax_id',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='length',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='package_preset',
            new_name='residential',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='packaging_type',
            new_name='state_tax_id',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='weight',
            new_name='validate_location',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='width',
        ),
        migrations.AddField(
            model_name='recipient',
            name='country_code',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone_number',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='postal_code',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='state_code',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='suburb',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
